[project]
name = "pytest-checkers"
version = "2.0.0"
description = "Pytest Plugin for dry-run checks LSPs, Type Checkers, Linters, and Formatters during testing"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "the-citto" }
]
classifiers = [
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
]
[project.urls]
Repository = "https://github.com/the-citto/pytest-checkers"

[project.entry-points."pytest11"]
checkers = "pytest_checkers.checkers"

[project.optional-dependencies]

[dependency-groups]
black = [
    "black>=26.10.0",
]
dev = [
    "ipython>=9.8.0",
]
flake8 = [
    "flake8>=7.4.1",
    "flake8-pyproject>=1.2.4",
]
isort = [
    "isort[colors]>=7.0.0",
]
isort-nocolor = [
    "isort>=7.0.0",
]
mypy = [
    "mypy>=1.19.0",
]
pyright = [
    "pyright[nodejs]>=1.1.407",
]
ruff = [
    "ruff>=0.16.10",
]
test = [
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "tox>=4.32.0",
    "tox-uv>=1.29.0",
]

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"

[tool.uv]
# CVE mitigations
override-dependencies = [
    "click>=8.3.3",
    "pygments>=2.20",
    "uv>=0.11.15",
    "virtualenv>=21.7.13",
]

[tool.pytest]
addopts = [
    "--strict-markers",
    "--no-header",
    # "--checkers",
]
testpaths = [
    "tests",
]

[tool.coverage.run]
omit = ["tests/*"]

[tool.tox]
requires = [
    "tox>=4.32.0",
    "tox-uv>=1.29.0"
]
isolated_build = true
env_list = [
    { product = [
        # ["linux", "windows"],
        ["3.14"],
        ["mindeps", "maxdeps"],
        ["checkers", "pyright", "mypy", "ruff", "flake8", "black", "isort", "isortnocolor"],
    ] },
]

[tool.tox.gh.python]
"3.14" = "py314"

[tool.tox.env_run_base]
package = "editable"
pass_env = ["PYTEST_ADDOPTS"]

uv_resolution = { replace = "if", condition = "factor.mindeps", then = "lowest-direct", else = "highest"}

deps = [
    ".",
]
dependency_groups = [
    { replace = "if", condition = "factor.checkers", then = ["test", "black", "flake8", "isort", "mypy", "pyright", "ruff"], extend = true },
    { replace = "if", condition = "factor.black", then = ["test", "black"], extend = true },
    { replace = "if", condition = "factor.flake8", then = ["test", "flake8"], extend = true },
    { replace = "if", condition = "factor.isort", then = ["test", "isort"], extend = true },
    { replace = "if", condition = "factor.isortnocolor", then = ["test", "isort-nocolor"], extend = true },
    { replace = "if", condition = "factor.mypy", then = ["test", "mypy"], extend = true },
    { replace = "if", condition = "factor.pyright", then = ["test", "pyright"], extend = true },
    { replace = "if", condition = "factor.ruff", then = ["test", "ruff"], extend = true },
]
commands = [
    { replace = "if", condition = "factor.checkers", then = [["pytest", "--checkers", { replace = "posargs", extend = true }]], extend = true },
    { replace = "if", condition = "factor.black", then = [["pytest", "tests/test_interface.py", "--checkers", { replace = "posargs", extend = true }]], extend = true },
    { replace = "if", condition = "factor.flake8", then = [["pytest", "tests/test_interface.py", "--checkers", { replace = "posargs", extend = true }]], extend = true },
    { replace = "if", condition = "factor.isort", then = [["pytest", "tests/test_interface.py", "--checkers", { replace = "posargs", extend = true }]], extend = true },
    { replace = "if", condition = "factor.isortnocolor", then = [["pytest", "tests/test_interface.py", "--checkers", { replace = "posargs", extend = true }]], extend = true },
    { replace = "if", condition = "factor.mypy", then = [["pytest", "tests/test_interface.py", "--checkers", { replace = "posargs", extend = true }]], extend = true },
    { replace = "if", condition = "factor.pyright", then = [["pytest", "tests/test_interface.py", "--checkers", { replace = "posargs", extend = true }]], extend = true },
    { replace = "if", condition = "factor.ruff", then = [["pytest", "tests/test_interface.py", "--checkers", { replace = "posargs", extend = true }]], extend = true },
]
set_env = [
    { replace = "if", condition = "factor.black", then = { TESTED_TOOLS = "black" }, else = {} },
    { replace = "if", condition = "factor.flake8", then = { TESTED_TOOLS = "flake8" }, else = {} },
    { replace = "if", condition = "factor.isort", then = { TESTED_TOOLS = "isort" }, else = {} },
    { replace = "if", condition = "factor.isortnocolor", then = { TESTED_TOOLS = "isort" }, else = {} },
    { replace = "if", condition = "factor.mypy", then = { TESTED_TOOLS = "mypy" }, else = {} },
    { replace = "if", condition = "factor.pyright", then = { TESTED_TOOLS = "pyright" }, else = {} },
    { replace = "if", condition = "factor.ruff", then = { TESTED_TOOLS = "ruff" }, else = {} },
]

[tool.pyright]
typeCheckingMode = "strict"
venvPath = "."
venv = ".venv"
stubPath = "typesheds"
ignore = [".venv/*"]

[tool.mypy]
strict = true
mypy_path = ["src", "tests", "typesheds"]
disallow_untyped_defs = true
exclude = ["build/*"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
preview = true
select = [ "ALL" ]
ignore = [
    "missing-copyright-notice",
    "incorrect-blank-line-before-class",
    # "blank-line-before-class",
    "multi-line-summary-second-line",
    # "multi-line-summary-first-line",
    "commented-out-code",
]

[tool.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "any-type",
    "docstring-missing-returns",
    "magic-value-comparison",
    "no-self-use",
    "assert",
]

[tool.flake8]
max-line-length = 120
exclude = [
    ".git", 
    ".venv",
    "__pycache__",
    ".tox",
    "typesheds/*",
]

[tool.black]
target-version = ["py313"]
line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
force_grid_wrap = 2

